In [35]:
"""Deleting , REmaining , Dropping duplicate , cleaning individual , remove the NaN values , check for some tranformation"""

'Deleting , REmaining , Dropping duplicate , cleaning individual , remove the NaN values , check for some tranformation'

In [17]:
import pandas as pd

In [18]:
data = pd.read_csv("Airbnb_Open_Data.csv")

C:\Users\dobar\AppData\Local\Temp\ipykernel_24204\180275767.py:1: DtypeWarning: Columns (0: license) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("Airbnb_Open_Data.csv")

In [19]:
data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='str')

In [20]:
columns_to_keep = [ 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review']

columns_to_drop = ['id' , 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license']

In [21]:
len(columns_to_keep)

19

In [22]:
len(columns_to_drop)

7

In [23]:
data.shape

(102599, 26)

# 1 Data Filtering

In [24]:
df = data[columns_to_keep]

In [25]:
print(df)

                                                    NAME      host id  \
0                     Clean & quiet apt home by the park  80014485718
1                                  Skylit Midtown Castle  52335172823
2                    THE VILLAGE OF HARLEM....NEW YORK !  78829239556
3                                                    NaN  85098326012
4       Entire Apt: Spacious Studio/Loft by central park  92037596077
...                                                  ...          ...
102594                        Spare room in Williamsburg  12312296767
102595                     Best Location near Columbia U  77864383453
102596                    Comfy, bright room in Brooklyn  69050334417
102597                  Big Studio-One Stop from Midtown  11160591270
102598                              585 sf Luxury Studio  68170633372

       host_identity_verified    host name neighbourhood group  \
0                 unconfirmed     Madaline            Brooklyn
1                    verified        Jenna           Manhattan
2                         NaN        Elise           Manhattan
3                 unconfirmed        Garry            Brooklyn
4                    verified       Lyndon           Manhattan
...                       ...          ...                 ...
102594               verified         Krik            Brooklyn
102595            unconfirmed        Mifan           Manhattan
102596            unconfirmed        Megan            Brooklyn
102597            unconfirmed  Christopher              Queens
102598            unconfirmed      Rebecca           Manhattan

              neighbourhood       lat      long        country country code  \
0                Kensington  40.64749 -73.97237  United States           US
1                   Midtown  40.75362 -73.98377  United States           US
2                    Harlem  40.80902 -73.94190  United States           US
3              Clinton Hill  40.68514 -73.95976  United States           US
4               East Harlem  40.79851 -73.94399  United States           US
...                     ...       ...       ...            ...          ...
102594         Williamsburg  40.70862 -73.94651  United States           US
102595  Morningside Heights  40.80460 -73.96545  United States           US
102596           Park Slope  40.67505 -73.98045  United States           US
102597     Long Island City  40.74989 -73.93777  United States           US
102598      Upper West Side  40.76807 -73.98342  United States           US

       instant_bookable cancellation_policy        room type  \
0                 False              strict     Private room
1                 False            moderate  Entire home/apt
2                  True            flexible     Private room
3                  True            moderate  Entire home/apt
4                 False            moderate  Entire home/apt
...                 ...                 ...              ...
102594            False            flexible     Private room
102595             True            moderate     Private room
102596             True            moderate     Private room
102597             True              strict  Entire home/apt
102598            False            flexible  Entire home/apt

        Construction year    price service fee  minimum nights  \
0                  2020.0    $966        $193             10.0
1                  2007.0    $142         $28             30.0
2                  2005.0    $620        $124              3.0
3                  2005.0    $368         $74             30.0
4                  2009.0    $204         $41             10.0
...                   ...      ...         ...             ...
102594             2003.0    $844        $169              1.0
102595             2016.0    $837        $167              1.0
102596             2009.0    $988        $198              3.0
102597             2015.0    $546        $109              2.0
102598             2010.0  $1,032        $206              1.0

        number of reviews last review
0                     9.0  10/19/2021
1                    45.0   5/21/2022
2                     0.0         NaN
3                   270.0    7/5/2019
4                     9.0  11/19/2018
...                   ...         ...
102594                0.0         NaN
102595                1.0    7/6/2015
102596                0.0         NaN
102597                5.0  10/11/2015
102598                0.0         NaN

[102599 rows x 19 columns]

# 2 data dropping

In [26]:
data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='str')

In [27]:
data.drop(columns= ['license'])

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and..."
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$368,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$204,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$844,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$837,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$988,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$546,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,"$1,032",$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN

In [28]:
data.drop(columns= columns_to_drop , inplace=True , errors= "ignore")

In [29]:
data.shape

(102599, 19)

# 3 Renaming the column

In [30]:
data.columns

Index(['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'],
      dtype='str')

In [31]:
data.rename(columns = {'NAME' : 'Name'})

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

In [32]:
data.rename(columns = {'NAME' : 'Name'},inplace = True)

In [33]:
data.columns

Index(['Name', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'],
      dtype='str')

In [40]:
new_column = []
for i in data.columns:
    new_column.append(i.upper())

In [41]:
new_df_to_modify = data.copy()

In [42]:
new_df_to_modify.columns = new_column

In [44]:
new_df_to_modify.columns

Index(['NAME', 'HOST ID', 'HOST_IDENTITY_VERIFIED', 'HOST NAME',
       'NEIGHBOURHOOD GROUP', 'NEIGHBOURHOOD', 'LAT', 'LONG', 'COUNTRY',
       'COUNTRY CODE', 'INSTANT_BOOKABLE', 'CANCELLATION_POLICY', 'ROOM TYPE',
       'CONSTRUCTION YEAR', 'PRICE', 'SERVICE FEE', 'MINIMUM NIGHTS',
       'NUMBER OF REVIEWS', 'LAST REVIEW'],
      dtype='str')

In [ ]:
data.duplicated()